- name: configuring mongodb server
  become: yes
  hosts: mongodb
  tasks:
  - name: copying mongodb repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: Installing mongodb server
    ansible.builtin.dnf:
      name: mongodb-org
      state: intalled

  - name: start and enable the MongoDB server
    ansible.builtin.server:
      name: mongodb
      state: started
      enabled: yes

  - name: allow remote connections
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: restart mongodb
    ansible.builtin.server:
      name: mongod
      state: restarted